name: Data-Owl tests
run-name: ${{ github.actor }} is testing tests on data owl
on: [push]
jobs:
  Test-Backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.test.txt ]; then pip install -r requirements.test.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Unit Tests
        run: |
          pytest
      - name: System Tests
        run: |
          .github/workflows/run_system_tests.sh
